hexatomic/hexatomic

- CONTRIBUTING.md
As discussed and documented in https://github.com/hexatomic/hexatomic.github.io/pull/12, we should publish our current code review schedules in the CONTRIBUTING.md file.
> Add code review schedule to CONTRIBUTING.md

- CHANGELOG.md
- bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/ProjectManager.java
- releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.target
- releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.tpd
If some (yet non-existing) editor deletes an existing object, the view won't update.
This is caused because only objects created after the view is created have the correct listener list.
This PR avoids the bug by keeping an internal list and proxy the notifications to the listeners in this internal list.
It also updates to Salt 3.3.9, which includes a bug fix where nodes can't be removed from graphs with notifications. 
Kind of, because we are not directly attaching the listeners to Salt anymore.
---
> Fix notification for nodes that have been created before the editor attached itself

- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestCorpusStructure.java
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGraphEditor.java
Issue Number: fixes #159 
The tests in the corpus structure editor where particular time sensitive, because renaming the example documents did not always work.
We are now using SWTKeyboardStrategy in the existing tests, which should give a more consistent behavior with `pressShortcut()`.
---
> Use SWTKeyboardStrategy consistently in all UI integration tests

- .travis.yml
- CHANGELOG.md
- bundles/org.corpus_tools.hexatomic.core/META-INF/MANIFEST.MF
- bundles/org.corpus_tools.hexatomic.corpusedit/META-INF/MANIFEST.MF
- bundles/org.corpus_tools.hexatomic.graph/META-INF/MANIFEST.MF
- bundles/org.corpus_tools.hexatomic.grid/META-INF/MANIFEST.MF
- bundles/org.corpus_tools.hexatomic.textviewer/META-INF/MANIFEST.MF
Until Eclipse is not bundling its own JVM, we should make sure to support as many JVMs as possible. Currently, Hexatomic neither runs nor is tested automatically on Java 11 (only on Java 8).
- Added an additional Java 11 configuration to Travis CI to make sure we don't introduce bugs on this platform
- Explicitly declare javax.annotation as dependency in the manifest file
- The workaround for <https://issues.apache.org/jira/browse/MNG-6765> has been removed from the Travis configuration, since Maven 3.6.3 is now used automatically. This enhances the readability of the configuration especially with multiple jobs present. 
- Reducing CI execution times by only …
> Fix Java 11 issues

- bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/graph/GraphEditor.java
- docs/user/src/usage/graph-editor/README.md
- features/org.corpus_tools.hexatomic/feature.xml
The current implementation of the segment calculation is executed in the UI thread when the filter has changed. Also, the tokens belonging to the segment are calculated in the UI thread whenever the selected segment changes 
Issue Number: this fixes #131  for me. Probably because before the UI thread was blocked for quite some time, not processing any more user interactions.
- Calculation which segments exist is done in a background job
- Calculating which tokens belong to a segment is done in a background job
- When the graph finished its layout after it a new segment was selected, the view automatically adjusts to show the first token and the complete height of the graph
- …
> Calculate graph segments and the tokens belonging to them in background

- bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/console/ConsoleController.java
- bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/console/ConsoleView.java
- bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/console/internal/SyntaxListener.java
- bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/graph/GraphEditor.java
- tests/org.corpus_tools.hexatomic.graph.tests/src/main/java/org/corpus_tools/hexatomic/console/TestConsoleController.java
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGraphEditor.java
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGridEditor.java
The `t` command in the console would only tokenize the first text of an annotation graph, regardless which textual data source was referenced by the current selected segment.
Issue Number: fixes #139 
- When a segment is selected, the new selected data source is propagated to the console
- If no segment is selected, the first text will be used as base for tokenization
This includes the commit PR #174  because the tests won't run otherwise
---
> Use currently selected text as base for tokenization

- CHANGELOG.md
- CITATION.cff
- pom.xml
- releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.target
- releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.tpd
- tests/org.corpus_tools.hexatomic.it.tests/pom.xml
The checkboxes are not properly drawn when selected and part of a dialog with grey background. This is a [long-standing bug in Eclipse](https://bugs.eclipse.org/bugs/show_bug.cgi?id=546552) which was fixed in their master branch some time ago, but has finally landed in a released Eclipse platform.
- Selected checkboxes on grey background are rendered correctly
- UI tests under Linux/GTK that are executed with Maven now always use the X11 server (and not Wayland, which seems to be buggy with SWTBot)
---
Follow the latest version of the [developer/maintainer docs](https://hexatomic.github.io/hexatomic/dev/) for making …
> Update Eclipse platform to 2020-03 to fix issue with checkboxes on GTK + Linux

- bundles/pom.xml
- docs/dev/src/development/automated-tests/README.md
- pom.xml
- tests/org.corpus_tools.hexatomic.tests.report/pom.xml
- tests/pom.xml
You can only create test coverage reports using the Eclipse Interface. Also the SonarCloud test coverage only pickups the test coverage of the tests itself, not the modules under test.
- Added a new aggregate test sub-project
- Documented how to generate an aggregated code coverage report in Maven
- Changed SonarCloud configuration to pickup the code coverage result of the aggregated report project.
- Fixed `mvn site` execution
---
> Aggregate test coverage results in Maven

- .gitignore
- CHANGELOG.md
- bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/style/LabelAccumulator.java
- docs/dev/src/development/automated-tests/ui-integration-tests.md
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestCorpusStructure.java
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGraphEditor.java
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGridEditor.java
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestHelper.java
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestProjectManager.java
Issue Number: #127 
This issue popped up again with failing tests on a system with `LANG=en_GB.UTF-8`.
Per default, SWTBot auto-detects the locale and tries to use the respective keyboard layout. Tests fail if it cannot be found for keyboard input.
- Fixes #127
- Explicitly sets the keyboard layout for SWTBot to `EN_US`, which is included in SWTBot.
- Tests may still fail if `en_US` is not available on a system at all, but this is explained in the dev docs.
---
> Fix issues with locale auto-detection in UI tests

- releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.target
- releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.tpd
Since this was updated to 3.0.0, our target platform did not work anymore. Using now the explicit release repository to avoid this problem in the feature.
Build is failing because the repository in the target platform does not contain the correct version of the plugin
- Using <https://download.eclipse.org/technology/swtbot/releases/2.8.0/> P2 repository
---
> SWTBot NatTable Repository was pointing to the "latest" release.

- bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/graph/GraphEditor.java
- docs/dev/src/development/automated-tests/README.md
- docs/dev/src/development/automated-tests/ui-integration-tests.md
- tests/org.corpus_tools.hexatomic.it.tests/META-INF/MANIFEST.MF
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGraphEditor.java
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestHelper.java
The GraphEditor test fails when trying to zoom in.
Issue Number: fixes #202 and provides an alternative fix for #127 (since #192 is partly reverted)
- Use the automatically detected keyboard layout for UI integration tests
- Allow to overwrite this with the SWTBOT_KEYBOARD_LAYOUT if necesary
- In addition to zooming in and out with <kbd>Ctrk</kbd>+<kbd>+</kbd>/<kbd>-</kbd> allow to use the <kbd>+</kbd> and <kbd>-</kbd> key of the keypad (<kbd>Ctrl</kbd> still needs to be pressed). This allows to make the test more locale independent and has the added benefit that a user with a keypad an US keyboard layout needs to press a key less.
--- …
> Allow to override keyboard layout and fix zoom in/out tests in GraphEditor

- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGridEditor.java
- Refactoring (no functional changes, no API changes)
Currently, `GridEditorTest` tests the absence of a specific context menu through calling the menu directly and waiting for a `WidgetNotFOundException`, which has a timeout penalty of 5000ms for each test. This leads to long waits during the tests.
- As in the two tests checking the above-mentioned conditions, no context menu should exist (yet) in the first place, the test is instead run to check that the parent menu is empty. This speeds up the UI tests by 10 whole seconds.
No.
---
- Check that …
> Speed up UI tests

- CHANGELOG.md
- bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/graph/GraphEditor.java
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGraphEditor.java
Bugfix (but not an urgent hot fix)
Empty documents with no tokens have the scale `0.0` which makes newly added token invisible.
Issue Number: #224 
- The constructor only zooms in onto the initial token when there are some
- Added a test case
N/A
---
> Do not change zoom when document does have any tokens

- CHANGELOG.md
- releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.target
- releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.tpd
Development setup issue
After updating the Eclipse IDE, the UI integration tests fail to run. According to [this Stackoverflow answer](https://stackoverflow.com/a/37160751/731040), this is because the IDE Junit runtime may fit the Eclipse runtime in one version, but not in another. The suggested solution is to add `org eclipse.pde.junit.runtime` to the target platform, which is what this pull request does. This fixes the issue.
- The UI Integration tests run independently of the JUnit Runtime packaged with the IDE, as it is packaged in the target platform.
No.
**(New dependency is not packaged with product)**
---
Follow the latest version of the [developer/maintainer …
> Fix target platform issue with running UI integration test from within Eclipse

- CHANGELOG.md
- bundles/org.corpus_tools.hexatomic.core/Application.e4xmi
- bundles/org.corpus_tools.hexatomic.corpusedit/src/main/java/org/corpus_tools/hexatomic/corpusedit/CorpusStructureView.java
Feature
At startup, the corpus structure editor takes 50% of the horizontal space of the whole view. Since we mostly want to edit the documents and not the structure, the lack of space for the actual editor is often very annoying.
- Using a 30% of the horizontal space for the corpus structure editor at startup (can be changed of course)
- Fixing an issue whre the text field of the filter was not resized when the corpus structure editor was smaller.
N/A
---
- Check that license and citation information for dependencies are complete …
> Tune ratio between corpus structure editor and editor parts

- CHANGELOG.md
- bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/GridHelper.java
- bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/internal/handlers/DisplayAnnotationRenameDialogOnCellsCommandHandler.java
- bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/internal/handlers/DisplayAnnotationRenameDialogOnColumnCommandHandler.java
- bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/internal/layers/GridColumnHeaderLayer.java
- tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/TestGridHelper.java
- tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/handlers/TestDisplayAnnotationRenameDialogOnColumnCommandHandler.java
- tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/layers/TestGridColumnHeaderLayer.java
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGridEditor.java
- Bugfix
Issue Number: #259
The annotation rename dialog shows the *display* name of the column rather than the actual annotation name (e.g., for the second column for a span annotation of `five::span_1` it shows `five::span_1 (2)`).
- Fix #259
- Rename dialog shows correct name
No
---
> Fix #259: Show correct annotation name on rename dialog

- .github/workflows/archive.yml
- CHANGELOG.md
- docs/dev/src/maintenance/continuous-integration/README.md
- Build related changes
Issue Number: #21
- Repository is never archived automatically on Software Heritage, unless it is crawled by them.
- Whenever a tag is pushed, the [SWH Save Action](https://github.com/marketplace/actions/save-to-software-heritage) is run, which triggers a call to the SWH API to save this repository.
- Fixes #21
No
---
> Set up auto archival trigger on tags push

- CHANGELOG.md
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/NoBackgroundJobsCondition.java
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGraphEditor.java
Test stability
The `TestGraphEditor.testTokenizeSelectedTextualDS` test occasionally failed because it attempted to select a text fragment before it was added to the view.
- Added a `NoBackgroundJobsCondition` which makes it easy to wait for all background jobs to finish. When a background task uses the `Job` API, this helper class should allow easy waiting and more stable test.
- Use this condition in the test
N/A
---
- Check that license and citation information for dependencies are complete (each dependency has a folder in …
> Wait until background job finishes in graph editor test

- CHANGELOG.md
- bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/ApplicationLifecycle.java
- bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/handlers/UpdateHandler.java
- bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/update/AppStartupCompleteEventHandler.java
- bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/update/UpdateRunner.java
- releng/ide/org.corpus_tools.hexatomic.product.launch
Refactoring (same feature, but better messaging)
There are ways the update check can fail, that the logic assumes that there might be an update available (the status code from the RCP `UpdateOperation` is not `STATUS_NOTHING_TO_UPDATE`, but get the `ProvisioningJob` still fails.
Currently, a message is shown that is clearly targeted at developers, reminding them that they should not start the update from a Eclipse debug run. But the issue can be triggered by other means and is shown to probably confused users.
Issue Number: closes #410
-  Limits the information a user needs to see. For background update checks, only a status message is shown. For manual checks, a dialog (with error log!) is shown.
- The error dialog is targeted at end users, and explains what happened and what might have …
> Show more explanations when update check fails

- CHANGELOG.md
- bundles/org.corpus_tools.hexatomic.formats/src/main/java/org/corpus_tools/hexatomic/formats/txt/TxtImportConfiguration.java
Bugfix
The layout for the text importer setting was broken, the checkbox was not aligned with its label.
Issue Number: fixes #420 
- The text importer settings dialog now uses the default grid data layout settings
N/A
---
> Fix #420 by removing unnecessary layout data

- CHANGELOG.md
- bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/Preferences.java
- bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/handlers/OpenSaltProjectHandler.java
- bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/console/ConsoleView.java
- bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/graph/GraphEditor.java
- docs/user/src/howtos/example-import.md
- docs/user/src/usage/graph-editor/README.md
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/graph/NoBackgroundJobsCondition.java
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/graph/TestGraphEditor.java
- tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/graph/ViewLocationReachedCondition.java
Feature
The user always has to type the full node name in the graph editor console when referencing it.
- When double clicking in the graph viewer above a node, the node name reference (e.g. `#n2`) will be appended to the console prompt
- The last loaded project location is stored as preference, so it is remembered when Hexatomic is restarted
N/A
---
> Insert node names in graph editor console on double click and remember opened project

- CHANGELOG.md
- CITATION.cff
- docs/dev/src/maintenance/contributions/manual-update-tests.md
- releng/org.corpus_tools.hexatomic.product/org.corpus_tools.hexatomic.p2.inf
- releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.target
When the build artifacts become too large (like including an unstripped JDK in the product), we can't upload the large files to GitHub pages anymore when releasing Hexatomic
If we enable Git LFS on the update site, artifacts queried using the current P2 URL because GitHub pages does not support LFS (https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage) and the update will fail.
- Use raw URLs to the assets in the GitHub repo instead of the GitHub pages URLs (e.g. https://raw.githubusercontent.com/octocat/Hello-World/master/README)
N/A
---
Follow the latest version of the …
> Prepare releases to use P2 repo on GitHub pages with Git LFS enabled
