.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Changes to the pull request template to remind maintainers to read the up-to-date release docs when making a release.
- There's a maintainer section in the PR template linking to the dev docs for releases
=> Change PR template to include maintainer section

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, docs/dev/src/SUMMARY.md, docs/dev/src/development/README.md, docs/dev/src/development/coding-style.md, docs/dev/src/development/setup.md, docs/dev/src/development/workflow/README.md, docs/dev/src/development/workflow/repositories.md, docs/dev/src/maintenance/README.md, docs/dev/src/maintenance/licensing/README.md, docs/dev/src/maintenance/pull-requests/README.md, docs/dev/src/maintenance/pull-requests/checklist.md, docs/dev/src/maintenance/releases/README.md, docs/dev/src/maintenance/releases/checklist.md
- GitHub templates changed (PR template)
Developer/maintainer docs aren't complete and include TODOs and FIXMEs
Issue Number: #65 
- Add dependencies and templates checks to PR template
- Update developer/maintainer documentation (#65)
-
Fixes #65.
Fixes #73.
Kept for future PRs:
- #58 
- #61 
- #48 
- #45 
- #32 
- #41
- #84
- #85
- #86
- #87
---
=> Update developer/maintainer docs for release

CONTRIBUTING.md
My working times have changed, to Wed afternoon-Fri afternoon, this should be reflected in the schedule.
As per the internal calendar, the current times are:
- TK: Thurs morning, Fri morning
- SD: Wed afternoon, Fri afternoon
Update of CONTRINBUTING.md to reflect up-to-date review schedule
CONTRIBUTING.md reflects old schedule
- CONTRIBUTING.md reflects new schedule
---
=> Update code review schedule

.travis.yml, CHANGELOG.md, features/org.corpus_tools.hexatomic/build.properties
CITATION.cff is not updated automatically during CI, and is not present in the product zips (#89).
- CITATION.cff is added to product roots, i.e., included in zips
- Travis update CFF during tag builds in the pre-deploy phase
- This should lead to up-to-date CFF files being included in product zips
This PR fixes #89 & is meant to lead to a patched release **v0.3.1**
---
=> Add up-to-date CFF to releases

bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/handlers/CloseSaltProjectHandler.java
=> Fix problem that will hit us in checkstyle 8.29

features/org.corpus_tools.hexatomic/feature.xml
It seems that the graph editor was not in the feature and thus e.g. starting a debug session left the developer without a graph editor in the context menu.
- Added the graph bundle as plugin to the hexatomic feature
---
=> Add graph editor to feature

CONTRIBUTING.md, docs/dev/src/introduction.md
Updated links to dev/user guide according to the current site layout
Issue Number: fixes #166 and fixes #167
- Some links in the documentation and CONTRIBUTION.md were refering to an older site layout
---
=> Fix broken links to dev and user documentation.

tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGraphEditor.java, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGridEditor.java
This fixes executing the tests from Eclipse (Maven did work before). The tests either provoked an invalid thread access or hang during the non-closed confirmation dialog.
- the `FORCE_CLOSE` parameter is set to true when opening new projects from integration tests
---
=> Force close when opening the project from the grid and graph integration tests.

CITATION.cff, releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.target
=> Update target platform to fix building the develop branch.

.travis.yml, pom.xml, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGridEditor.java
We are not using an external code analysis tool (like Findbugs or reporting the test coverage)
- Added integration with https://sonarcloud.io/, which provides static code analysis and comments on pull requests about potential issues
- The configuration in Travis is kept as a separate build job to not affect the release and JDK 8/11 testing
- Executing the UI tests and recording the code coverage seems to influence the timing. I had to make some UI test more stable these timing effects, e.g. with explicit waits. Also, by some mysterious reason, maximizing the window does not work properly. I maximize the grid editor part inside Hexatomic instead.
Only to Travis CI configuration, …
=> Add Travis CI configuration for SonarCloud static code analysis

README.md
The second badge shows the wrong number of contributors anyway ;).
- Removes broken duplicate all contributors badge
-
-
---
=> Remove duplicate all-contributors badge

bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/graph/internal/SaltGraphLayout.java
=> Fix some issues in the SaltGraphLayout class found by static code analysis

.travis.yml, pom.xml, tests/pom.xml
- Test coverage should now be reported by SonarCloud
---
=> Configure test coverage for SonarCloud

bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/console/ConsoleController.java, bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/graph/GraphEditor.java, bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/graph/MouseZoomOrScrollListener.java, docs/user/src/usage/graph-editor/README.md, tests/org.corpus_tools.hexatomic.it.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/PartActiveCondition.java, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/PartMaximizedCondition.java, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGraphEditor.java, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGridEditor.java, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/ViewLocationReachedCondition.java
Static code analysis reported many issues in the `GraphEditor` class, including issues with readability because of too long and nested methods. This class alone contributed to a lot of the "Maintainability" score.
Also, the test coverage was very insufficient.
- Fixed all reported issues from SonarCloud in the `GraphEditor` class.
- Added more test cases. Because it is impossible to test  mouse wheels and we did the zoom exclusively with the mouse wheel, I added the <kbd>CTRL</kbd>+<kbd>+</kbd> <kbd>CTRL</kbd>+<kbd>-</kbd> shortcuts which also perform zoom. This new feature is documented, everything else is just refactoring
---
Follow the …
=> Refactor graph editor and add more tests

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Documentation content changes
Currently, the checkboxes also are used to mark alternatives.
Unfortunately in the PR overview, the checkboxes are interpreted as a task do be done and PRs appear to never be finished because not all "tasks" have been checked.
Issue Number: fixes #199
- This re-formulates and re-organizes the PR template so that every PR should have all checkbox item checked when finished.
- The order is also updated so that the description comes first and than the checklist
N/A
---
- License and citation information for dependencies are …
=> Update pull request template to only use checkboxes in the checklist.

.travis.yml
We have at least 8 parallel build jobs per PR.
- Merged OpenJDK and Sonarcloud to one job (the latter one did everything the first did plus some more stuff)
- Don't build pushed branches except develop/master and the feature release branches. This should avoid some blockage when multiple PRs are merged into develop and we reach the current overall limit for concurrent build jobs for a project.
N/A
---
- Check that license and citation information for dependencies are complete (each dependency has a folder in …
=> Reduce number of parallel CI jobs

.travis.yml, CHANGELOG.md, bundles/org.corpus_tools.hexatomic.core/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.corpusedit/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.graph/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.graph/pom.xml, bundles/org.corpus_tools.hexatomic.grid/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.textviewer/META-INF/MANIFEST.MF, bundles/pom.xml, features/org.corpus_tools.hexatomic/feature.xml, features/org.corpus_tools.hexatomic/pom.xml, features/pom.xml, pom.xml, releng/org.corpus_tools.hexatomic.product/pom.xml, releng/org.corpus_tools.hexatomic.target/pom.xml, releng/org.corpus_tools.hexatomic.update/pom.xml, releng/pom.xml, tests/org.corpus_tools.hexatomic.core.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.graph.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.grid.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.it.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.it.tests/pom.xml, tests/org.corpus_tools.hexatomic.tests.report/pom.xml, tests/pom.xml
Bugfix
Tagged commits are not built at all in Travis so no release binaries are created and added to the release on GitHub.
- Versioned release tags are built, these are defined on a regular expression which matches our tags
N/A
---
=> Include tagged release commits in Travis configuration

.travis.yml, CHANGELOG.md, bundles/org.corpus_tools.hexatomic.core/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.corpusedit/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.graph/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.graph/pom.xml, bundles/org.corpus_tools.hexatomic.grid/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.textviewer/META-INF/MANIFEST.MF, bundles/pom.xml, features/org.corpus_tools.hexatomic/feature.xml, features/org.corpus_tools.hexatomic/pom.xml, features/pom.xml, pom.xml, releng/org.corpus_tools.hexatomic.product/pom.xml, releng/org.corpus_tools.hexatomic.target/pom.xml, releng/org.corpus_tools.hexatomic.update/pom.xml, releng/pom.xml, tests/org.corpus_tools.hexatomic.core.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.graph.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.grid.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.it.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.it.tests/pom.xml, tests/org.corpus_tools.hexatomic.tests.report/pom.xml, tests/pom.xml
- Bugfix
N/A
Travis deployment fails due to bad config:
```yaml
[error] on services: dropping unknown value: metacity
[warn] on jobs.include.deploy.token.secure: invalid value on secure string: {:secure=>"$GITHUB_TOKEN"}
[warn] on jobs.include.deploy: deprecated key: "skip_cleanup" (not supported in dpl v2, use cleanup)
[warn] on jobs.include.deploy: deprecated key: "skip_cleanup" (not supported in dpl v2, use cleanup)
[info] on jobs.include.deploy: the key api_key is an alias for token, using token
[info] on root: missing language, using the default "ruby"
[info] on root: missing dist, using the default "xenial"
```
- Removed `metacity` from list of `services`
- Rename `api_key` key to `token` and remove bad `secure:` key
- Use dpl2 by adding `edge: true` to deploy …
=> Fix Travis config

CHANGELOG.md, docs/dev/src/development/workflow/README.md, docs/dev/src/maintenance/releases/README.md
- The hotfix workflow said to merge unreviewed hotfix PRs via administrator rights, this is wrong. Instead, the hotfix release process should be followed
- The hotfix release section included a typo
- Change last enumerated item in unreviewed hotfix section to reflect correct workflow
- Fix typo in hotfix releases section
N/A
---
=> Fix release documentation for hotfixes

bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/errors/HexatomicRuntimeException.java, bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/Column.java, bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/ColumnHeaderDataProvider.java, bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/GraphDataProvider.java, bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/GridDisplayConverter.java, bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/LabelAccumulator.java, bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/RowHeaderDataProvider.java, tests/org.corpus_tools.hexatomic.core.tests/src/main/java/org/corpus_tools/hexatomic/core/TestProjectManager.java, tests/org.corpus_tools.hexatomic.graph.tests/src/main/java/org/corpus_tools/hexatomic/console/TestConsoleController.java, tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/bindings/TestFreezeGridBindings.java, tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/TestColumn.java, tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/TestColumnHeaderDataProvider.java, tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/TestGraphDataProvider.java, tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/TestGridDisplayConverter.java, tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/TestLabelAccumulator.java, tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/TestRowHeaderDataProvider.java, tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/style/TestSelectionStyleConfiguration.java, tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/style/TestStyleConfiguration.java
Refactoring
Several places throw a generic `RuntimeException` instead of using an application specific one.
See <https://sonarcloud.io/organizations/hexatomic/rules?open=java%3AS112&rule_key=java%3AS112> why using generic exceptions is considered bad practice.
- Introducing the application specific `HexatomicRuntimeException`
- This PR also removes various generic `throws Exception` declarations in the test cases: these were not actually needed because the called functions either did not throw any exception at all, or only runtime exceptions which do not need and should not declare them in their function declaration.
N/A
---
Follow the latest version of the …
=> Add a specific Hexatomic runtime exception and use it instead of the generic one

CHANGELOG.md, docs/user/src/troubleshooting.md
Documentation content changes
- User documentation contains a link to the mailing list for users.
N/A
---
=> Add mailing list link to user docs

.github/workflows/test.yml, .travis.yml, CHANGELOG.md, docs/dev/src/development/workflow/repositories.md
We use Travis CI (.com) for testing all pull requests
- Automated tests are executed on OpenJDK 8 using GitHub Actions
- Automated tests are executed on OpenJDK 11 using GitHub Actions and code analysis is uploaded to SonarCloud
- Building the documentation with mdbook is tests
These are three different jobs that will be executed in parallel.
N/A
---
=> Add GitHub Actions workflow to execute the automated tests

README.md
Note: *not* built locally with `mvn clean verify`.
- Build related changes
README.md displays a build shield for Travis.
README.md displays a build shield for GitHub Actions
No.
---
=> Replace Travis shield with GitHub Actions shield

CHANGELOG.md, pom.xml, releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.target, releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.tpd, tests/org.corpus_tools.hexatomic.core.tests/META-INF/MANIFEST.MF
I have problems in another PR with executing the tests via Maven, while executing them with Eclipse was no issue. I wanted to check if this might be a problem that has been fixed in later versions of Tycho (the current  version 1.6.0 is quite old). Just updating Tycho to the newer release 1.7.0 failed, so I did this PR to add the necessary changes, so we can use an up-to-date Tycho version.
Tycho 2.x can't be used as long as we want to stay compatible with Java 8.
- Uses Tycho 1.7.0
- Update Eclipse Platform to 2020-06
- Update Eclipse Orbit Repo to R20201130205003
N/A
---
Follow the latest version of the [developer/maintainer …
=> Update Tycho version to 1.7.0

CHANGELOG.md, bundles/org.corpus_tools.hexatomic.core/Application.e4xmi, bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/handlers/AboutHandler.java, bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/handlers/OpenOnlineDocumentationHandler.java, bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/ui/AboutDialog.java, docs/user/src/troubleshooting.md, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestHelpMenu.java
Feature
There is currently now way for the user to get the Hexatomic version from the UI and/or any pointers were to find help.
- Add  menu entry to open "About" dialog with version number derived from the core bundle version (should be in sync with product)
- Add menu entry with link to current version of the online documentation
N/A
---
=> Add "About" dialog and links to online documentation

.mvn/extensions.xml, pom.xml
We use tycho 1.7.0 as Maven plugins  and 1.4.0 as Maven extension for pom-less builds.
- Unify version of both the Maven plugins and extensions to updated 1.7.0 (the last version that supports Java 8)
N/A
---
=> Update Tycho Extension to version 1.7.0

CHANGELOG.md, bundles/org.corpus_tools.hexatomic.core/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.corpusedit/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.formats/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.graph/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.graph/pom.xml, bundles/org.corpus_tools.hexatomic.graph/src/main/antlr4/org/corpus_tools/hexatomic/console/ConsoleLexer.g4, bundles/org.corpus_tools.hexatomic.grid/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.textviewer/META-INF/MANIFEST.MF, bundles/pom.xml, features/org.corpus_tools.hexatomic/feature.xml, features/org.corpus_tools.hexatomic/pom.xml, features/pom.xml, pom.xml, releng/org.corpus_tools.hexatomic.product/pom.xml, releng/org.corpus_tools.hexatomic.target/pom.xml, releng/org.corpus_tools.hexatomic.update/pom.xml, releng/pom.xml, tests/org.corpus_tools.hexatomic.core.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.formats.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.graph.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.graph.tests/src/main/java/org/corpus_tools/hexatomic/console/TestConsoleController.java, tests/org.corpus_tools.hexatomic.grid.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.it.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.it.tests/pom.xml, tests/org.corpus_tools.hexatomic.tests.report/pom.xml, tests/pom.xml
Bugfix
Non-Ascii characters can't be used in tokenize (`t`) command in the graph editor. It is possible to quote them, but this is quite cumbersome.
Issue Number: fixes #261 
- All Unicode letter characters are allowed as identifier in the graph console
- "ideographic full stop" as is treated as punctuation character
N/A
---
=> Hotfix/0.5.1 for #261

.github/ISSUE_TEMPLATE/feature_request.md, README.md
Workflow-related
Issue Numbers: #19, #120 
- @clachenmaier and @bunz-lightyear added as core contributors to README (fixes #120)
- Feature request includes line for reporters to add themselves to all-contributors list (fixes #19, see https://github.com/hexatomic/hexatomic/issues/19#issuecomment-797609348)
No
---
=> Enable contribution crediting

README.md, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestProjectManager.java
Documentation content changes and added test
We don't report any SonarCloud metrics in our README
Issue Number: closes #245 
- Added badge for the SonarCloud badges from the dashboard to the README (Quality Gate, the different ratings and code coverage)
- Add test for exiting with unsaved changes warning dialog to get code coverage for the one changed line since the release, otherwise the quality gate will be reported as "failed"
N/A
---
- Check that license and citation information for dependencies are complete (each dependency has a folder in …
=> Add SonarCloud badges

CITATION.cff, bundles/org.corpus_tools.hexatomic.core/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.corpusedit/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.formats/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.graph/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.graph/pom.xml, bundles/org.corpus_tools.hexatomic.grid/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.textviewer/META-INF/MANIFEST.MF, bundles/pom.xml, features/org.corpus_tools.hexatomic/feature.xml, features/org.corpus_tools.hexatomic/pom.xml, features/pom.xml, pom.xml, releng/org.corpus_tools.hexatomic.product/pom.xml, releng/org.corpus_tools.hexatomic.target/pom.xml, releng/org.corpus_tools.hexatomic.update/pom.xml, releng/pom.xml, tests/org.corpus_tools.hexatomic.core.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.formats.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.graph.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.grid.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.it.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.it.tests/pom.xml, tests/org.corpus_tools.hexatomic.tests.report/pom.xml, tests/pom.xml
We are using the non-snapshot version "0.5.1" in the develop branch
- We use "0.6.0-SNAPSHOT" as version
N/A
---
=> Set version to 0.6.0-SNAPSHOT

docs/dev/src/development/automated-tests/README.md, docs/dev/src/development/automated-tests/ui-integration-tests.md, docs/dev/src/development/getting-the-source-code.md
Issue Number: #193 
- It is more intuitive to have detailed information on how to run UI
tests headlessly in the section on UI tests
- Move the respective section there
- Link to the UI tests section from both "Getting the source code"
and "Automated tests"
- Fix #193
No
---
=> Move section on running UI tests headlessly

CHANGELOG.md, docs/dev/src/SUMMARY.md, docs/dev/src/common-issues/README.md
- Fixes #278
Issue Number: #278 
- Developer documentation contains a new section *Common issues* to provide a list of commonly encountered issues during development.
No
---
=> Add common issues section to developer documentation

CHANGELOG.md, docs/dev/src/SUMMARY.md, docs/dev/src/development/documentation/README.md, docs/dev/src/development/setup.md
Issue Number: #58 It isn't documented how to document Hexatomic
- Developer/maintainer documentation contains a section on documentation (fixes #58)
- Following a documentation style is suggested there, and the Google dev doc style guide is linked (fixes https://github.com/hexatomic/hexatomic.github.io/issues/17)
No.
---
=> Add developer section to dev docs

CHANGELOG.md, docs/dev/src/SUMMARY.md, docs/dev/src/maintenance/README.md, docs/dev/src/maintenance/continuous-integration/README.md
Use of continuous integration isn't documented.
Issue Number: #84
No
---
=> Document continuous integration

.github/workflows/test.yml, docs/dev/src/maintenance/continuous-integration/README.md
Actions aren't run on pull requests from forks.
- Activates the test workflow to be run also on pull requests
No
---
=> Activate test action to be run on PRs

.github/workflows/test.yml
- Build related changes
Issue Number: #303
Workflows are run twice on pushes to pull requests with source branches in this repository.
- While #304 isn't solved, there's no need to trigger runs via `pull_request`, hence this is removed from the test workflow
- Fixes #303
No
---
=> Remove pull_request event trigger for test workflow

.github/workflows/test.yml, CHANGELOG.md, docs/dev/src/maintenance/README.md, docs/dev/src/maintenance/releases/README.md, docs/dev/src/maintenance/taking-over/README.md
Issue Number: https://github.com/hexatomic/hexatomic/issues/318
- Add a section on notifying the community of new releases to the maintenance documentation
- Mention mailing list usage in takeover notes for new maintainers
- Add mailing list to maintenance task list
- No
To review this PR, please check the SonarCloud quality summary on my branch first.
You will have to look at the one-to-last commit, as the last commit removes the sonar properties I'm using for my branch (which won't work for you): https://github.com/stephandruskat/hexatomic/runs/2932672615.
---
Follow the latest version of the [developer/maintainer …
=> Fix #318: Add promoting releases to the community to dev docs

tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGridEditor.java
- Bugfix
As described in https://github.com/hexatomic/hexatomic/pull/267#issuecomment-995546791, the manual refresh integration tests cause some issues, due to timing: when the test progresses too quickly, the visual update hasn't happened yet and the tests fail.
- Conditions are used to let the GUI test bot wait until they are met.
- Tests keep failing when the conditions aren't met, but they pass when the conditions are met.
No
---
- Check that license and citation information for dependencies are complete (each dependency has a folder in …
=> Fix timing issue in GUI tests

CHANGELOG.md, docs/user/src/usage/grid-editor/README.md
Fixes #361
- Adds tables for grid editor keyboard shortcuts to the bottom of the main grid editor section in the user docs
- Improves the introductory description of the grid editor
No
---
=> Document keybindings

CHANGELOG.md, bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/style/StyleConfiguration.java, tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/style/TestStyleConfiguration.java
- Refactoring (no functional changes, no API changes)
- #173
- The Grid Editor now uses the `ColorPalette`'s blueish green to display span annotation values.
- This fixes #173
No
---
=> Use consistent colours from palette in Grid Editor

CHANGELOG.md, docs/dev/src/development/setup.md, pom.xml, releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.target, releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.tpd
We suggest developers to use the Eclipse IDE 2019-06 or newer. But with the newest Eclipse IDE version 2021-12, the UI and other plugin tests can't be executed. There is an error message about a missing class `org/junit/platform/engine/support/hierarchical/HierarchicalTestEngine` and it seems to be an incompatibility issue between the old platform and the test execution runner in newer Eclipse versions.
- Updated the Eclipse platform to 2021-12
- Updated Tycho to 2.7.0, because the older versions seems to be incompatible with the new platform as well
- Updated documentation not to recommend the outdated Eclipse IDE version 
This should not change the functionality of any known plugin.
--- …
=> Update target platform to 2021-12 so we can execute tests in newer Eclipse versions

.github/workflows/release.yml, CHANGELOG.md, bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/update/UpdateRunner.java, docs/dev/src/maintenance/releases/README.md, releng/org.corpus_tools.hexatomic.product/p2.inf
Issue Number: fixes  #288
- An additional build job is added to the "release" workflow that builds and publishes the P2 repo to https://hexatomic.github.io/updates/
- Changed the update site to point to https://hexatomic.github.io/updates/v0 which is its own repository
N/A
Tested by creating a new branch from this one and executing the following steps
---
=> Add GitHub Action to automatically publish the P2 repo on release

CHANGELOG.md, bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/ui/AboutDialog.java
- Bugfix
The About page shows qualified build information, but the qualifier information will only be available in locally built versions between releases, and these versions arguably aren't supported for end use.
Issue Number: #383
- The About page doesn't show any qualified build information.
No
---
=> Fix #383: Remove useless build information from About page

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, CONTRIBUTING.md, README.md, docs/dev/src/development/getting-the-source-code.md, docs/dev/src/development/workflow/README.md, docs/dev/src/development/workflow/repositories.md, docs/dev/src/development/workflow/setup.md, docs/dev/src/introduction.md, docs/dev/src/maintenance/README.md, docs/dev/src/maintenance/contributions/README.md, docs/dev/src/maintenance/releases/README.md, docs/dev/src/maintenance/unreviewed-code-triage.md, docs/user/src/introduction.md, docs/user/src/troubleshooting.md, pom.xml
- Other: prepares the code base for a change in branching model
Issue Number: #333
The production branch is called `master`.
- Production branch is renamed to `main` in documentation files, GitHub workflow, template files
- Maven Gitflow Plugin is configured to accept `main` as the production branch.
-
No
---
=> #333: Rename master branch

CITATION.cff, releng/templates/CITATION.cff
- Other: Updates the metadata in the `CITATION.cff` template
Issue Number: #387
This is a prerequisite PR for fixing #387.
- Complete and update metadata in the CFF file
- Tested by: 
- running `mvn cff:create` and checking whether `date-released` and `version` are being updated :heavy_check_mark: 
- creating a test release to see if the info pulls over to Zenodo Sandbox :heavy_check_mark: 
Test results: the info from `CITATION.cff` is pulled over to Zenodo Sandbox nicely :tada: 
No
---
- Check that license and citation information for dependencies are …
=> Update CITATION.cff template with metadata and format file

.github/workflows/metadata.yml, .github/workflows/release.yml, .github/workflows/test.yml
When tests are executed in GitHub Actions, we need to install metacity. Currently, we assume the apt metadata is up to date.
Not updating means the mirror servers and other things can be out of date.
This can lead to errors e.g. about not found mirror servers.
- Execute `sudo apt-get update` before installing metacity
N/A
---
=> Update apt metadata before trying to install metacity.

.github/workflows/metadata.yml, CITATION.cff
N/A
The metadata update workflow fails when no changes to the citation or dependency files are made. Also, the "cff" profile is not actually executed.
- Don't return an in the GitHub Action workflow error when the commit is empty.
- Activate cff profile with `-Pcff`
- Dont run tests in metadata update workflow: there is a different workflow doing this already
N/A
---
=> Actually activate cff profile when running the workflow.

CHANGELOG.md, CITATION.cff, pom.xml, releng/templates/tukaani.xz.yml
Build-related changes
Issue Number: Fixes #387
- CFF file is invalid due to license `OTHER` for bundle org.tukaani.xz, which is not in the SPDX license list, and therefore invalidates the CFF file
- `CITATION.cff` contains no DOI for the work
- Add reference template for bundle `org.tukaani.xz` and let the POM pick it up
- Update CFF files via `mvn -Pcff package`
- Add Zenodo collection DOI  to CFF
N/A
---
=> Fix plugin metadata and add Zenodo collection DOI to CFF

CITATION.cff, releng/templates/CITATION.cff
- Bugfix
The `doi` key and `identifiers` section is automatically removed from `CITATION.cff` during release workflow, as it is automatically updated from the template, which doesn't contain the section and key.
- Add `doi` key to root, and `identifiers` section to `CITATION.cff`
No
---
=> Add DOI to CFF template as root key and identifier

CHANGELOG.md, CITATION.cff, docs/dev/src/maintenance/releases/README.md
- The release docs say to publish release first, then wait for "binaries" to be added
- The release docs don't mention the Zenodo publication
- Swap bullets in GitHub release dev docs to say to wait for binaries to be attached, then press "Publish release"
- Docs now also mention that everytime a release is being made, a Zenodo publication is made and a new version DOI minted
No
---
=> Improve release section in dev docs

.github/workflows/release.yml, CHANGELOG.md, CITATION.cff, bundles/org.corpus_tools.hexatomic.core/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.corpusedit/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.formats/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.graph/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.graph/pom.xml, bundles/org.corpus_tools.hexatomic.grid/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.textviewer/META-INF/MANIFEST.MF, bundles/pom.xml, features/org.corpus_tools.hexatomic/feature.xml, features/org.corpus_tools.hexatomic/pom.xml, features/pom.xml, pom.xml, releng/org.corpus_tools.hexatomic.product/p2.inf, releng/org.corpus_tools.hexatomic.product/pom.xml, releng/org.corpus_tools.hexatomic.target/pom.xml, releng/org.corpus_tools.hexatomic.update/pom.xml, releng/pom.xml, tests/org.corpus_tools.hexatomic.core.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.formats.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.graph.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.grid.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.it.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.it.tests/pom.xml, tests/org.corpus_tools.hexatomic.tests.report/pom.xml, tests/pom.xml
Bugfix
We still use the old v0 update site URL, but our major version is now "1"
- Configure the v1 update site URLs 
- Update the GitHub action to create the v1 folder instead of v0
N/A
After the release, we have to manually copy the v1 folder as v0 folder in the https://github.com/hexatomic/updates repository so people who downloaded 1.0.0 get the updated 1.0.1
---
=> Create and use v1 update site (hotfix)

CHANGELOG.md, docs/user/src/installation.md
Documentation content change
Issue Number: relates to #409 
Updated the documentation to reflect that
- No Unzip needed on Safari
- Command line run is confusing for normal users and additional information they need to parse, with unknown terms. Moved into a footnote
N/A
---
=> Clarify Mac OS installation instructions in user documentation.

CHANGELOG.md, bundles/org.corpus_tools.hexatomic.corpusedit/src/main/java/org/corpus_tools/hexatomic/corpusedit/CorpusStructureView.java, tests/org.corpus_tools.hexatomic.core.tests/src/main/java/org/corpus_tools/hexatomic/core/TestProjectManager.java, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestCorpusStructure.java
Bugfix
When deleting a document in the corpus structure editor, no checkpoint was set.
Thus, the deletion could not be undone.
Issue Number: #422 
- Add checkpoint when deleting an element in the corpus structure editor
N/A
---
=> Allow undoing deleting documents

CHANGELOG.md, CITATION.cff, bundles/org.corpus_tools.hexatomic.core/Application.e4xmi, bundles/org.corpus_tools.hexatomic.core/plugin.xml, releng/org.corpus_tools.hexatomic.product/org.corpus_tools.hexatomic.product, tests/org.corpus_tools.hexatomic.it.tests/UI Integration Test.launch, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestGraphEditor.java, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestHelpMenu.java
Feature
Issue Number: closes #413 
- Use standardized command name for properties
- Rename product to "Hexatomic" so it is probably displayed on macOS
N/A
---
=> Use standardized command name for properties

CITATION.cff, NOTICE, releng/templates/CITATION.cff
Documentation content changes
Issue Number: Fixes #414 
We have a not so common approach to list our third-party dependencies in the CITATION.cff file in the references section. The NOTICE file is a much more obvious place to look for this list, so add the NOTICE file and explain where to find the needed information. This is more or less the same phrasing as in the "About" dialog.
Also, this adds the Font Awesome reference to CITATION.cff template.
N/A
---
- Check that license and citation information for dependencies are complete (each dependency has …
=> Add Font Awesome to citation file and add NOTICE file.

CHANGELOG.md, CITATION.cff, bundles/org.corpus_tools.hexatomic.core/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.corpusedit/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.formats/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.formats/src/main/java/org/corpus_tools/hexatomic/formats/CorpusFormatSelectionPage.java, bundles/org.corpus_tools.hexatomic.formats/src/main/java/org/corpus_tools/hexatomic/formats/exporter/ExporterSelectionPage.java, bundles/org.corpus_tools.hexatomic.formats/src/main/java/org/corpus_tools/hexatomic/formats/importer/ImporterSelectionPage.java, bundles/org.corpus_tools.hexatomic.graph/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.graph/pom.xml, bundles/org.corpus_tools.hexatomic.grid/META-INF/MANIFEST.MF, bundles/org.corpus_tools.hexatomic.textviewer/META-INF/MANIFEST.MF, bundles/pom.xml, features/org.corpus_tools.hexatomic/feature.xml, features/org.corpus_tools.hexatomic/pom.xml, features/pom.xml, pom.xml, releng/org.corpus_tools.hexatomic.product/org.corpus_tools.hexatomic.product, releng/org.corpus_tools.hexatomic.product/pom.xml, releng/org.corpus_tools.hexatomic.target/pom.xml, releng/pom.xml, tests/org.corpus_tools.hexatomic.core.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.formats.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.graph.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.grid.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.it.tests/META-INF/MANIFEST.MF, tests/org.corpus_tools.hexatomic.it.tests/pom.xml, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestImportExport.java, tests/org.corpus_tools.hexatomic.tests.report/pom.xml, tests/pom.xml
N/A
The export wizard shows formats for selection that can't be exported.
Issue Number: fixes #458 
- Only the formats that can be exported are shown
N/A
---
=> Only show the formats suitable for export in the wizard page.

CHANGELOG.md, CITATION.cff, tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/utils/SwtBotChips.java
Refactoring
A more or less costly operation is executed for logging debug messages in `SwtBotChips`, even if debug is not enabled in the tests.
Issue Number: Fixes #456
- Only call the logging function when debug is enabled.
N/A
---
=> Only calculate the text of the widget if logging is in debug mode.
